# For more information about the available options please visit: http://go/catalog-info (VPN required)
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    github.com/project-slug: Unity-Technologies/go-lager-internal
    backstage.io/techdocs-ref: dir:.
  name: go-lager-internal
  description: "Logs (from golang) in JSON, easy for computers to parse, people to read, programmers to generate.  Efficient."
  labels:
    costcenter: "7151"
spec:
  type: service
  lifecycle: experimental
  owner: Unity-Technologies/unity-services-foundation
